---
- hosts: g1
  become: yes
  tasks:
    - name: Update package cache and install build tools (Ubuntu)
      apt:
        name:
          - python3
          - python3-pip
          - build-essential
          - python3-dev
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache and install build tools (CentOS)
      yum:
        name:
          - python3
          - python3-pip
          - gcc
          - python3-devel
        state: present
      when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

    - name: Install Flask dependencies
      pip:
        name:
          - uwsgi  # Example dependency, adjust as needed
        state: present

    - name: Copy Flask app files
      synchronize:
        src: /path/to/your/flask/app
        dest: /var/www/flask_app
        delete: yes
      become: yes
      tags:
        - deploy

    - name: Set up uWSGI service
      systemd:
        name: uwsgi
        enabled: yes
        state: started
        daemon_reload: yes
      become: yes
      tags:
        - configure
