---
- name: Deploy Flask App
  hosts: g1
  become: yes

  tasks:
    - name: Update package cache and install build tools (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - python3-pip

    - name: Update package cache and install build tools (CentOS)
      when: ansible_distribution == 'CentOS'
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - gcc-c++
        - python2-pip

    - name: Update package cache and install build tools (Amazon Linux)
      when: ansible_distribution == 'Amazon'
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - gcc-c++
        - python3-pip

    - name: Install Flask dependencies
      pip:
        name: uwsgi
        state: present

    - name: Copy Flask app files
      command: "rsync --delay-updates -F --compress --delete-after --archive --rsh=/usr/bin/ssh -S none -i /home/centos/linux.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --rsync-path=sudo rsync --out-format=<<CHANGED>>%i %n%L /path/to/your/flask/app {{ ansible_user }}@{{ ansible_host }}:/var/www/flask_app"
      delegate_to: localhost
