- name: Setup Flask Environment and Deploy Flask Web App
  hosts: all
  become: true
  remote_user: root
  gather_facts: true

  tasks:
    - name: update package cache and install git (Ubuntu)
      when: ansible_pkg_mgr == "apt"
      apt:
        name: git
        state: present

    - name: update package cache and install git (CentOS)
      when: ansible_pkg_mgr == "yum"
      yum:
        name: git
        state: present

    - name: update package cache and install git (Amazon Linux)
      when: ansible_pkg_mgr == "dnf"
      yum:
        name: git
        state: present

    - name: install python3-venv package (Ubuntu)
      when: ansible_pkg_mgr == "apt"
      apt:
        name: python3-venv
        state: present

    - name: install python3-venv package (CentOS)
      when: ansible_pkg_mgr == "yum"
      yum:
        name: python3-venv
        state: present

    - name: install python3-venv package (Amazon Linux)
      when: ansible_pkg_mgr == "dnf"
      yum:
        name: python3-venv
        state: present

    - name: remove existing flask_dir
      file: 
        path: ~/flask_dir
        state: absent
      ignore_errors: yes

    - name: clone git repository
      git:
        repo: https://github.com/caligha/flask_web_app.git
        dest: ~/flask_dir/
 
