- name: Setup Flask Environment and Deploy Flask Web App
  hosts: all
  become: true
  remote_user: root
  gather_facts: true

  tasks:
    - name: update package cache
      package_facts:
      when: ansible_pkg_mgr == "apt"

    - name: install necessary packages for apt
      apt: 
        name: 
          - python3-pip
          - python3-dev
          - build-essential
          - git
          - ufw
        state: present 
      when: ansible_pkg_mgr == "apt"

    - name: update package cache
      package_facts:
      when: ansible_pkg_mgr == "dnf"

    - name: Install necessary packages for dnf 
      dnf:
        name:
          - python3-pip
          - python3-devel
          - python3-venv
          - git
        state: present
      when: ansible_pkg_mgr == "dnf"

    - name: remove existing flask_dir
      file: 
        path: ~/flask_dir
        state: absent
      ignore_errors: yes

    - name: clone git repository
      git:
        repo: https://github.com/caligha/flask_web_app.git
        dest: ~/flask_dir/
        version: main

    - name: create virtual environment
      command: python3 -m venv ~/flask_dir/.myenv

    - name: activate virtual environment
      command: /bin/bash -c "source ~/flask_dir/.myenv/bin/activate"

    - name: set Flask app environment variables
      set_fact:
        flask_app_env:
          FLASK_APP: "~/flask_dir/app.py"
          FLASK_RUN_HOST: "0.0.0.0"
          FLASK_RUN_PORT: "5000"

    - name: start flask web app
      command: /bin/bash -c "{{ flask_app_env | to_json | b64encode | b64decode }} && flask run &"
